services:
  mosquitto:
    image: eclipse-mosquitto:2
    container_name: mosquitto
    volumes:
      - ./config/:/mosquitto/config/
      - ./log/:/mosquitto/log/
      - ./data:/mosquitto/data/
    ports:
      - 1883:1883
      - 9001:9001